### ISSUE TITLE
having trouble defining the file_path_input and image names in boxer function

### ISSUE THREAD

**Issue by marireeves** [stomperusa/boundingbox#1]
Hi There - I've been trying to get the boundingbox boxer function to run on a stream of photos. 

They are in a folder on my drive as in: 
TrainPicDir<- 'C:/Users/marireeves/Documents/Lehua/ImagesTrain/'

What I would usually do for batch file processing is create a list of the files as in:
trainpics<-list.files(TrainPicDir, full.names = T, pattern = "*.png")

Then run whatever loop or process on them from there...e.g., 
classy<-boxer(
names = trainpics[1:10],

but when I try that strategy with the following file path input:
file_path_input = system.file("extdata", package = "boundingbox"),

I get this error: 
Error in wrap.url(file, load.image.internal) : File not found

I also initially thought from the documentation that I should define the file_path_input as my directory name, e.g.,
file_path_input = system.file("ImagesTrain", package = "boundingbox"), 

but with that, I get the following error:
Error in checksList[[n]]() : file_path_input not found

I also tried just file_path_input = TrainPicDir
where
TrainPicDir<- 'C:/Users/marireeves/Documents/Lehua/ImagesTrain/'
but that yields the 
Error in wrap.url(file, load.image.internal) : File not found
also. 
I've also tried making lists of full names or partial names of the png or jpg files themselves, but then am getting errors regarding file format..

So I'm just not sure from the documentation how to specify the names and the file_path_input and am wondering if you can provide some help?

**Comment by stomperusa** [comment]
Hi there. Let me first thank you for using my package.  I am sorry you are having difficulty with the boxer() function.

In the package there is a directory called “extdata” and that is where the pictures are stored for my example. System.file is used to extract the files from within the package. You just want to assign your own directory as you have with file_path_input = TrainPicDir.

The issue you are having is that when you run list.files() you want to set full.names = F, otherwise you end up with the full path to your files. The name parameter of the boxer() function just wants the file names, and the file_path_input parameter wants the path. With that, I expect file_path_input = TrainPicDir should work for you. 

Best of luck and let me know if you are still having trouble after trying that. 

Regards,

DS
